name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Build macOS Application
    runs-on: macos-latest
    strategy:
      matrix:
        architecture: [x86_64, arm64]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest'

      - name: Build .app for ${{ matrix.architecture }}
        run: |
          xcodebuild -project billboard.xcodeproj -scheme billboard -configuration Release -arch ${{ matrix.architecture }} -derivedDataPath derivedData
          cp -r "derivedData/Build/Products/Release/billboard.app" "Billboard.app"
          
      - name: Archive .app for ${{ matrix.architecture }}
        run: |
          zip -r "billboard-${{ matrix.architecture }}.zip" "Billboard.app"
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: billboard-${{ matrix.architecture }}
          path: billboard-${{ matrix.architecture }}.zip

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
      - name: Debug
        run: ls -al
      - name: Create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./**/billboard-x86_64.zip
            ./**/billboard-arm64.zip
